### PR TITLE
Fill in covariance matrices of Livox IMU

### LINKED ISSUE #2: Fill in covariance matrices of Livox IMU
The covariance matrices must not be zero. Otherwise, the Kalman filter of the `oxin_localisation` package will fail.

This change will be based on [this approach](https://github.com/ros-drivers/microstrain_3dmgx2_imu/blob/indigo-devel/src/imu_node.cc#L142-L160).

### PR DESCRIPTION
**Pull request by eborghi10**
The covariance matrices must not be zero. Otherwise, the Kalman filter of the `oxin_localisation` package will fail.

**Note:** We should check these changes in an Oxin robot.

### CODE REVIEW

File: livox_ros_driver/livox_ros_driver/lddc.cpp [hunk 1]
```diff
@@ -518,6 +518,22 @@ uint32_t Lddc::PublishImuData(LidarDataQueue *queue, uint32_t packet_num,
...
   imu_data.linear_acceleration.z = imu->acc_z;
 
+  // Fill in covariance matrices
+  cur_node_->param("angular_velocity_stddev", angular_velocity_stddev_, kDefaultAngularVelocityStdDev_);
+  cur_node_->param("linear_acceleration_stddev", linear_acceleration_stddev_, kDefaultLinearAccelerationStdDev_);
+
+  const double angular_velocity_covariance = angular_velocity_stddev_ * angular_velocity_stddev_;
+  const double linear_acceleration_covariance = linear_acceleration_stddev_ * linear_acceleration_stddev_;
+
+  imu_data.angular_velocity_covariance[0] = angular_velocity_covariance;
```
Comment (dmbuck32) [inline livox_ros_driver/livox_ros_driver/lddc.cpp]: I'm not quite sure why we're doing this. According to the IMU message documentation: 

    # If the covariance of the measurement is known, it should be filled in (if all you know is the 
    # variance of each measurement, e.g. from the datasheet, just put those along the diagonal)
    # A covariance matrix of all zeros will be interpreted as "covariance unknown", and to use the
    # data a covariance will have to be assumed or gotten from some other source
    #
    # If you have no estimate for one of the data elements (e.g. your IMU doesn't produce an orientation 
    # estimate), please set element 0 of the associated covariance matrix to -1
    # If you are interpreting this message, please check for a value of -1 in the first element of each 
    # covariance matrix, and disregard the associated estimate.

> A covariance matrix of all zeros will be interpreted as "covariance unknown"

It's perfectly valid to have an empty covariance matrix.

Comment (eborghi10) [reply livox_ros_driver/livox_ros_driver/lddc.cpp]: Because the Kalman filter needs to have realistic covariance values to work properly. I should set the first element of the orientation covariance to -1 according to this text since the IMU does not provide orientation.

Comment (dmbuck32) [reply livox_ros_driver/livox_ros_driver/lddc.cpp]: I found a similar issue in a different repo: 
- https://github.com/ros-drivers/microstrain_mips/issues/19
- https://github.com/ros-drivers/microstrain_mips/pull/20

It looks like a similar fix, except that they populate the covariance matrix directly:
https://github.com/ros-drivers/microstrain_mips/blob/master/launch/microstrain.launch#L54

Is it more correct to populate it the way that you've done it?

Comment (eborghi10) [reply livox_ros_driver/livox_ros_driver/lddc.cpp]: It's a valid point. In fact, it seems more clear to understand.
I already pushed the changes.

File: livox_ros_driver/launch/livox_hub.launch [hunk 2]
```diff
@@ -14,23 +14,26 @@
...
+		<param name="publish_freq" type="double" value="$(arg publish_freq)"/>
+		<param name="output_data_type" value="$(arg output_type)"/>
+		<param name="cmdline_str" type="string" value="$(arg bd_list)"/>
+		<param name="cmdline_file_path" type="string" value="$(arg lvx_file_path)"/>
+		<param name="user_config_path" type="string" value="$(find livox_ros_driver)/config/livox_hub_config.json"/>
+		<param name="lidar_frame_id" type="string" value="$(arg lidar_msg_frame_id)"/>
+		<param name="imu_frame_id" type="string" value="$(arg imu_msg_frame_id)"/>
+		<param name="enable_lidar_bag" type="bool" value="$(arg lidar_bag)"/>
+		<param name="enable_imu_bag" type="bool" value="$(arg imu_bag)"/>
+		<param name="angular_velocity_cov" type="double" value="$(arg angular_velocity_cov)"/>
```
Comment (dmbuck32) [inline livox_ros_driver/launch/livox_hub.launch]: does this work with the array? I would have thought that the `type="double"` would expect a single value.

Comment (eborghi10) [reply livox_ros_driver/launch/livox_hub.launch]: Good catch! It's done.

**Comment by eborghi10** [comment]
@dmbuck32 Please take a look again.

File: livox_ros_driver/livox_ros_driver/lddc.cpp [hunk 3]
```diff
@@ -518,6 +518,21 @@ uint32_t Lddc::PublishImuData(LidarDataQueue *queue, uint32_t packet_num,
   imu_data.linear_acceleration.y = imu->acc_y;
   imu_data.linear_acceleration.z = imu->acc_z;
 
+  // Fill in covariance matrices
+  cur_node_->param("angular_velocity_cov", angular_velocity_cov_, kDefaultAngularVelocityCov_);
```
Comment (dmbuck32) [inline livox_ros_driver/livox_ros_driver/lddc.cpp]: I'm thinking that these covarance matrices should be set on class construction, rather than having to look up the covarance matrix from the ros param server on every IMU message.

Comment (dmbuck32) [reply livox_ros_driver/livox_ros_driver/lddc.cpp]: We're publishing the IMU data at a rate of ~200Hz, so the cost to access the param server is probably non-negligible.

Comment (dmbuck32) [reply livox_ros_driver/livox_ros_driver/lddc.cpp]: Do we expect these covariance values to be updated during runtime?

**Review by dmbuck32 — CHANGES_REQUESTED** [review]

File: livox_ros_driver/livox_ros_driver/lddc.cpp (hunk 3 above)
Comment (eborghi10) [reply livox_ros_driver/livox_ros_driver/lddc.cpp]: Very good point. For now, we don't want to update the covariances during runtime. In the future, we could use "dynamic reconfigure".

Comment (eborghi10) [reply livox_ros_driver/livox_ros_driver/lddc.cpp]: I applied your suggestion.

File: livox_ros_driver/livox_ros_driver/lddc.cpp [hunk 4]
```diff
@@ -98,6 +97,24 @@ Lddc::~Lddc() {
   }
 }
 
+void Lddc::SetRosNode(ros::NodeHandle *node) {
+  cur_node_ = node;
+
+  // Fill in covariance matrices
```
Comment (dmbuck32) [inline livox_ros_driver/livox_ros_driver/lddc.cpp:107]: I don't like his this increases the scope of the `SetRosNode()` function. I think that we should have a new function `lddc::SetImuCovarance()` that this logic could be put into.

File: livox_ros_driver/livox_ros_driver/lddc.cpp [hunk 5]
```diff
@@ -493,8 +510,7 @@ uint32_t Lddc::PublishImuData(LidarDataQueue *queue, uint32_t packet_num,
   uint64_t timestamp = 0;
   uint32_t published_packet = 0;
 
-  sensor_msgs::Imu imu_data;
-  imu_data.header.frame_id.assign(imu_frame_id_);
+  imu_data_.header.frame_id.assign(imu_frame_id_);
```
Comment (dmbuck32) [inline livox_ros_driver/livox_ros_driver/lddc.cpp]: Why'd you add the IMU sensor message as a class member?

**Review by dmbuck32 — CHANGES_REQUESTED** [review]

File: livox_ros_driver/livox_ros_driver/lddc.cpp (hunk 5 above)
Comment (eborghi10) [reply livox_ros_driver/livox_ros_driver/lddc.cpp]: Because I'm modifying the covariances only once and to save some time setting some constant values on each loop, the message is defined as a class member.

File: livox_ros_driver/livox_ros_driver/lddc.cpp [hunk 6]
```diff
@@ -99,7 +101,9 @@ Lddc::~Lddc() {
 
 void Lddc::SetRosNode(ros::NodeHandle *node) {
   cur_node_ = node;
+}
 
+void Lddc::SetImuCovariances() {
```
Comment (dmbuck32) [inline livox_ros_driver/livox_ros_driver/lddc.cpp:106]: what calls `SetImuCovariances()`?

Comment (dmbuck32) [reply livox_ros_driver/livox_ros_driver/lddc.cpp:106]: I've gone ahead and added a call to it in both the node and nodelet initialisations.

**Review by dmbuck32 — APPROVED** [review]
I think it looks good, can you make sure that my changes work for you?

File: livox_ros_driver/livox_ros_driver/lddc.cpp (hunk 6 above)
Comment (eborghi10) [reply livox_ros_driver/livox_ros_driver/lddc.cpp:106]: Good catch :facepalm:
