### PR TITLE
Fix non-nodelet node

### LINKED ISSUE #9: Livox node is not detecting ROS parameters

### PR DESCRIPTION
**Pull request by eborghi10**
```
roslaunch lidar_algorithms livox.launch nodelet:=false
```

**NOTE:** Nodelet approach is still not working

Fixes #9.

### CODE REVIEW

File: livox_ros_driver/livox_ros_driver/lddc.cpp [hunk 1]
```diff
@@ -679,6 +683,9 @@ ros::Publisher *Lddc::GetCurrentPublisher(uint8_t handle) {
           name_str, queue_size);
     }
   }
+  else {
+    std::runtime_error("Couldn't find a suitable publisher for Livox Lidar");
```
Comment (dmbuck32) [inline livox_ros_driver/livox_ros_driver/lddc.cpp]: I don't think that this is correct... it looks like the logic is ensuring that a publisher exists, even if one hasn't been created before.

Comment (eborghi10) [reply livox_ros_driver/livox_ros_driver/lddc.cpp]: What do you propose? Reverting the change?

Comment (dmbuck32) [reply livox_ros_driver/livox_ros_driver/lddc.cpp]:
```
if publisher doesn't exist:
    create publisher
    set pub pointer
else
    // Do nothing.
    
return pointer to publisher
```

File: livox_ros_driver/livox_ros_driver/livox_ros_driver_nodelet.cpp [hunk 2]
```diff
@@ -194,9 +195,7 @@ namespace livox_ros
       poll_freq = 2000;
     }
 
-    const ros::Timer poll_lidars = private_node_handle.createTimer(ros::Duration(ros::Rate(poll_freq)), &LivoxRosDriverNodelet::proccessLidarLoop, this);
-
-    return;
+    poll_lidars_ = private_node_handle.createTimer(ros::Duration(ros::Rate(poll_freq)), &LivoxRosDriverNodelet::proccessLidarLoop, this);
```
Comment (dmbuck32) [inline livox_ros_driver/livox_ros_driver/livox_ros_driver_nodelet.cpp:198]: do we need to save this timer as a class member?

File: livox_ros_driver/livox_ros_driver/lddc.cpp (hunk 1 above)
Comment (eborghi10) [reply livox_ros_driver/livox_ros_driver/lddc.cpp]: Ok, reverted.

File: livox_ros_driver/livox_ros_driver/livox_ros_driver_nodelet.cpp (hunk 2 above)
Comment (eborghi10) [reply livox_ros_driver/livox_ros_driver/livox_ros_driver_nodelet.cpp:198]: Yes, otherwise the timer callback is never called.

File: livox_ros_driver/livox_ros_driver/lddc.cpp [hunk 3]
```diff
@@ -683,9 +683,6 @@ ros::Publisher *Lddc::GetCurrentPublisher(uint8_t handle) {
           name_str, queue_size);
     }
```
Comment (dmbuck32) [inline livox_ros_driver/livox_ros_driver/lddc.cpp:684]: Add handling for an invalid `transfer_format_`.

Comment (eborghi10) [reply livox_ros_driver/livox_ros_driver/lddc.cpp:684]: Done.

**Review by dmbuck32 — APPROVED** [review]
LGTM
