### PR TITLE
Fix nodelet

### LINKED ISSUE #10: Livox nodelet not publishing topics
Topics are not published with `roslaunch livox_ros_driver livox_lidar_nodelet.launch`.

Related to #8 because it needs some changes introduced there.

----

Working branch: https://github.com/oxin-ros/livox_ros_driver/tree/hotfix/livox-nodelet-pub

EDIT: There seems to be a problem with the version of GCC: https://github.com/ros/diagnostics/issues/119#issuecomment-1027169155

### LINKED ISSUE #13: Investigate intermittent Livox lidar connection issues
While testing out the deployment of the code in a docker container, I noticed that the livox lidar would occasionally fail to output data on the ROS topic. This task is for figuring out why this occurs and to fix the issue.

### PR DESCRIPTION
**Pull request by eborghi10**
This PR fixes the error in the nodelet implementation (`std::bad_alloc`) by using smart pointers.

### CODE REVIEW

File: livox_ros_driver/livox_ros_driver/lddc.cpp [hunk 1]
```diff
@@ -633,89 +603,86 @@ void Lddc::DistributeLidarData(void) {
   }
 }
 
-ros::Publisher *Lddc::GetCurrentPublisher(uint8_t handle) {
-  ros::Publisher **pub = nullptr;
+std::shared_ptr<ros::Publisher> Lddc::GetCurrentPublisher(uint8_t handle) {
+  std::shared_ptr<ros::Publisher> pub {};
```
Comment (dmbuck32) [inline livox_ros_driver/livox_ros_driver/lddc.cpp]:
```suggestion
  std::shared_ptr<ros::Publisher> pub = nullptr;

```

File: livox_ros_driver/livox_ros_driver/lddc.cpp [hunk 2]
```diff
@@ -633,89 +603,86 @@ void Lddc::DistributeLidarData(void) {
...
 
-  return *pub;
+  global_pub_ = pub;
+  return pub;
 }
 
-ros::Publisher *Lddc::GetCurrentImuPublisher(uint8_t handle) {
-  ros::Publisher **pub = nullptr;
+std::shared_ptr<ros::Publisher> Lddc::GetCurrentImuPublisher(uint8_t handle) {
+  std::shared_ptr<ros::Publisher> pub{};
```
Comment (dmbuck32) [inline livox_ros_driver/livox_ros_driver/lddc.cpp]:
```suggestion
  std::shared_ptr<ros::Publisher> pub = nullptr;

```

**Review by dmbuck32 — CHANGES_REQUESTED** [review]
Could you explicitly initialise the shared pointers with nullptr?

**Review by dmbuck32 — APPROVED** [review]
LGTM.
